### ISSUE TITLE
New version crashes

### ISSUE THREAD

**Issue by Moldx3** [leopoko/solclassic#1]
Hey!

i just saw your mod and downloaded the newest version.
Sadly it crashes during startup.
I downloaded an older version and it works.

No crash report is created and no information is available inside the log files.

The mod is a great idea!

Info:
MC Version 1.20.1
Forge: forge-1.20.1-47.3.10-installer
Mods installed:
Loading 165 mods:
	- accessories 1.0.0-beta35+1.20.1
		|-- fabric_api_base 0.4.31+ef105b4977
		|-- fabric_data_attachment_api_v1 1.0.0+30ef839e77
		|-- fabric_entity_events_v1 1.6.0+6274ab9d77
		\-- fabric_object_builder_api_v1 11.1.3+2174fc8477
	- advancementplaques 1.6.7
	- allurement 4.0.0
	- amendments 1.20-1.2.11
		\-- mixinextras 0.3.6
	- animal_feeding_trough 1.1.0+1.20.1-forge
	- appleskin 2.5.1+mc1.20.1
	- aquaculture 2.5.2
	- archers_paradox 5.0.0
	- architectury 9.2.14
	- ars_nouveau 4.12.4
	- arsnouveaudelight 1.0.3-1.20.1
	- artifacts 9.5.13
		\-- expandability 9.0.4
	- auto_restart 2.0.2
	- awesomedungeon 3.2.0
	- awesomedungeonend 3.1.1
	- awesomedungeonnether 3.1.1
	- awesomedungeonocean 3.3.0
	- badoptimizations 2.1.4
	- balm 7.3.9
		\-- kuma_api 20.1.8
	- betteradvancements 0.4.2.10
	- betterdeserttemples 1.20-Forge-3.0.3
	- betterdungeons 1.20-Forge-4.0.4
	- betterendisland 1.20-Forge-2.0.6
	- betterfortresses 1.20-Forge-2.0.6
	- betterjungletemples 1.20-Forge-2.0.5
	- bettermineshafts 1.20-Forge-4.0.4
	- betteroceanmonuments 1.20-Forge-3.0.4
	- betterstrongholds 1.20-Forge-4.0.3
	- betterwitchhuts 1.20-Forge-3.0.3
	- biomesoplenty 18.0.0.598
	- blueprint 7.1.0
	- bookshelf 20.2.13
	- bountiful 6.0.3+1.20.1
	- brutalbosses 1.20.1-7.1
	- caelus 3.2.0+1.20.1
	- canary 0.3.3
	- carbonconfig 1.20-1.2.6
	- cataclysm 1.99.5
	- chunkpregen 1.20-4.4.4
	- citadel 2.6.0
	- cloth_config 11.1.136
	- clumps 12.0.0.4
	- cofh_core 11.0.2
	- collective 7.84
	- comforts 6.4.0+1.20.1
		\-- spectrelib 0.13.15+1.20.1
	- corgilib 4.0.3.2
	- craftingtweaks 18.2.5
	- create 0.5.1.h
		\-- flywheel 0.6.11-13
	- cristellib 1.1.5
	- ctov 3.4.9
	- culllessleaves 1.20.1-1.0.5
	- cupboard 1.20.1-2.7
	- curios 5.10.0+1.20.1
	- deeperdarker 1.3.2
	- dixtas_armory 1.1.9-1.20.1-beta
	- dummmmmmy 1.20-2.0.2
	- dungeoncrawl 2.3.14
	- dungeonnowloading 1.5
	- dungeons_arise 2.1.58-1.20.x
	- dungeons_plus 1.5.0
	- dynamic_fps 3.7.3
	- elytraslot 6.4.3+1.20.1
		\-- mixinsquared 0.1.2-beta.6
	- emi 1.1.13+1.20.1+forge
	- enchdesc 17.1.18
	- endrem 5.3.3-R-1.20.1
	- enhancedcelestials 1.20.1-5.0.1.0
	- entityculling 1.7.0
	- farmersdelight 1.20.1-1.2.4
	- fastfurnace 8.0.2
	- ferritecore 6.0.1
	- firstaid 1.20.1-1.1
	- foodvariation 1.04
	- forge 47.3.10
	- framework 0.7.8
	- geckolib 4.4.9
	- goblintraders 1.9.3
	- goodending 1.20.1-1.0.1
	- graveyard 3.1
	- iceandfire 2.1.13-1.20.1
	- iceberg 1.1.21
	- immediatelyfast 1.2.21+1.20.4
	- insanelib 1.15.0
	- jei 15.19.5.99
	- kambrik 6.1.1+1.20.1
	- kotlinforforge 4.11.0
	- libraryferret 4.0.0
	- lionfishapi 1.9
	- lithostitched 1.3.0
	- lootr 0.7.34.87
	- mcwbridges 3.0.0
	- minecraft 1.20.1
	- modernfix 5.19.4+mc1.20.1
	- moonlight 1.20-2.13.0
	- moremobvariants 1.3.0.1
	- mowziesmobs 1.6.4
	- mr_dungeons_andtaverns 3.0.3.f
	- mr_vanilla_refresh 1.4.19h
	- mutant_iceologer 2.0.1
	- mutantmonsters 8.0.7
	- mutil 6.1.1
	- mysticaloaktree 1.20-1.11
	- nethersdelight 1.20.1-4.0
	- nochatreports 1.20.1-v2.2.2
	- noisium 2.3.0+mc1.20-1.20.1
	- notenoughanimations 1.7.6
	- nullscape 1.2.8
	- openpartiesandclaims 0.23.2
	- ore_creeper 1.20.1-1.2.1
	- phantasm 0.4.1
	- placebo 8.6.2
	- pmmo 1.4.25
	- progressivebosses 3.9.7-mc1.20.1
	- puzzleslib 8.1.23
		\-- puzzlesaccessapi 8.0.7
	- quark 4.0-460
	- repurposed_structures 7.1.15+1.20.1-forge
	- ribbits 1.20.1-Forge-3.0.0
	- roughlyenoughitems 12.1.780
	- sereneseasons 9.0.0.46
	- smoothchunk 1.20.1-3.6
	- sons_of_sins 2.1.6
	- sound_physics_remastered 1.20.1-1.4.5
	- spark 1.10.53
	- sparsestructuresreforged 1.20.1-0.0.1
	- spelunkers_charm 3.6.0
	- starterkit 7.1
	- structory 1.3.5
	- structure_gel 2.16.2
	- supplementaries 1.20-2.8.17
	- t_and_t 0.0NONE
	- taxtg 1.1.0
	- tectonic 2.4.1
	- terrablender 3.0.1.7
	- terralith 2.5.4
	- tetra 6.4.0
	- tlc 1.0.2
	- totw_modded 1.0.5
	- toughasnails 0.0NONE
	- travelersbackpack 9.1.15
	- twilightforest 4.3.2508
	- upgrade_aquatic 6.0.1
	- valhelsia_core 1.1.2
	- valhelsia_structures 1.20.1-1.1.2
	- valhelsia_tweaks 0.1.0
	- vc_gliders 1.1.5
		|-- palladiumcore 1.20-2.0.0.0
		\-- playeranimator 1.0.2-rc1+1.20
	- villagernames 8.1
	- waystones 14.1.5
	- xaerominimap 24.4.0
	- xaeroworldmap 1.39.0
	- xpbook 2.2.1
	- yungsapi 1.20-Forge-4.0.5
	- yungsbridges 1.20-Forge-4.0.3
	- zeta 1.0-24

**Comment by leopoko** [comment]
@Moldx3 Thank you for reporting this issue! I will look into it. By the way, could you let us know which version of the mod you were using — was it 1.03 or 1.02?

**Comment by Moldx3** [comment]
Thanks! 

I downloaded 1.05 and it crashed and 1.04 works. If you Need more just let me know.

**Comment by leopoko** [comment]
@Moldx3 I have released version 1.06! Hopefully, the issue is fixed. Thank you for your report! The difference between version 1.04 and 1.06 is only the change in the logo and the name.
