### ISSUE TITLE
Suggestion: Compat with nutritional balance and diet

### ISSUE THREAD

**Issue by mxnmnm** [leopoko/solclassic#2]
Can we get compat for these mods (or at least one of them?):

https://www.curseforge.com/minecraft/mc-mods/nutritional-balance
https://www.curseforge.com/minecraft/mc-mods/diet

By compat I mean that the lunch box should be able to also see which foods match your nutritional needs and take that into account along with the frequency of the food eaten.

**Comment by leopoko** [comment]
First, I would like to make it compatible with DIET. Thanks for the suggestion.

**Comment by leopoko** [comment]
In ver1.13, wickerbasket is now compatible with Nutritional Balance. tooltip notation has not been fixed yet, but it is usable for now. Thank you for your patience.
