### ISSUE TITLE
Basket duplicates food

### ISSUE THREAD

**Issue by EndilCrafter** [leopoko/solclassic#3]
https://github.com/user-attachments/assets/5ec4dcaa-6eb8-4a0e-9c35-a069cf01e194

any of 1~9 key -> duplicate

**Comment by leopoko** [comment]
報告ありがとうございます！調査します

**Comment by leopoko** [comment]
ver1.10にて修正しました。配信され次第試してみてください～！ご報告ありがとうございました！！
