### ISSUE TITLE
Crashes when hovering over Pizza in Pizza Delight

### ISSUE THREAD

**Issue by sumire0nekoneko** [leopoko/solclassic#4]
As the title says.
Crashes with the following error when hovering over Pizza in Pizza Delight ([url](https://www.curseforge.com/minecraft/mc-mods/pizza-delight))

java.lang.NullPointerException: Cannot invoke "net.minecraft.world.food.FoodProperties.m_38744_()" because the return value of "net.minecraft.world.item.Item.m_41473_()" is null

Use mods
appleskin-forge-mc1.20.1-2.5.1.jar
FarmersDelight-1.20.1-1.2.4.jar
pizzadelight-1.20.1-1.0.0.jar
solclassic-1.11.jar

The image is a screenshot under the Appleskin installation.
![image](https://github.com/user-attachments/assets/3fe235e2-1159-43af-af51-dcfae9594d97)

crashreport
[crash-2024-10-23_12.23.47-client.txt](https://github.com/user-attachments/files/17484794/crash-2024-10-23_12.23.47-client.txt)

**Comment by leopoko** [comment]
Fixed in ver 1.12! Please try it out~
