### ISSUE TITLE
The client crashes when the mouse hovers over crossroads:edible_blob

### ISSUE THREAD

**Issue by NHblock714** [leopoko/solclassic#5]
[crash-2024-10-23_23.05.59-client.txt](https://github.com/user-attachments/files/17494277/crash-2024-10-23_23.05.59-client.txt)

**Comment by leopoko** [comment]
Thanks for the report. We will investigate.

**Comment by leopoko** [comment]
This problem has been resolved in ver1.12. Please try using it! Thank you~
